use_frameworks!

platform :ios, '9.0'

target 'WJTimerClockLabel_Example' do
  pod 'WJTimerClockLabel', :path => '../'

  target 'WJTimerClockLabel_Tests' do
    inherit! :search_paths

    
  end
end
